 # Ball detection notebook
 _by Paul-Emmanuel sotir_

In [3]:
import os
import sys
import shutil
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
from torch.utils.data import DataLoader

from importlib import reload

if '../src/balldetect' not in sys.path:
    sys.path.append('../src/balldetect')
import datasets
reload(datasets)

#CONDA_ENV = 'generalization_training'

ModuleNotFoundError: No module named 'hyperopt'

In [2]:
# Torch configuration
use_gpu = torch.cuda.is_available()
cudnn.benchmark = use_gpu  # Enable inbuilt CuDNN auto-tuner TODO: measure preformances without this flag
cudnn.fastest = use_gpu  # Disable this if memory issues

In [3]:
dataset = datasets.BallsCFDetection("../datasets/mini_balls")
dl = DataLoader(dataset, batch_size=64, shuffle=True, pin_memory=use_gpu)

In [5]:
from skimage import io
img = np.asarray(io.imread("../datasets/mini_balls/img_00000.jpg"))
img = img.astype(np.float32)
img = np.transpose(img, (2, 0, 1))
img = torch.tensor(img, dtype=torch.float32)
img

tensor([[[148., 161., 198.,  ..., 219., 201., 208.],
         [161., 157., 149.,  ..., 216., 198., 213.],
         [160., 141., 160.,  ..., 222., 192., 205.],
         ...,
         [153., 153., 153.,  ..., 150., 166., 190.],
         [153., 153., 153.,  ..., 150., 150., 158.],
         [153., 153., 153.,  ..., 150., 148., 152.]],

        [[148., 162., 204.,  ..., 215., 200., 207.],
         [158., 158., 154.,  ..., 212., 197., 212.],
         [155., 138., 160.,  ..., 218., 191., 204.],
         ...,
         [153., 153., 153.,  ..., 150., 166., 190.],
         [153., 153., 153.,  ..., 150., 150., 158.],
         [153., 153., 153.,  ..., 150., 148., 152.]],

        [[138., 156., 200.,  ..., 212., 198., 205.],
         [149., 152., 150.,  ..., 209., 195., 210.],
         [149., 133., 158.,  ..., 215., 189., 202.],
         ...,
         [153., 153., 153.,  ..., 150., 166., 190.],
         [153., 153., 153.,  ..., 150., 150., 158.],
         [153., 153., 153.,  ..., 150., 148., 152.]]]

In [136]:
bbs = np.array([bb for img, p, bb in dataset])

In [ ]:
(imgs, bbs) = zip(*np.array([(img.tolist(), bb) for img, p, bb in dataset]))

In [129]:
bbs = bbs / np.max(bbs, axis=(0, 1))[np.newaxis, np.newaxis, :]
imgs = imgs / np.max(imgs, axis=(0, 2, 3))[np.newaxis, :, np.newaxis, np.newaxis]

In [135]:
bbs[0]

array([[0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.898876, 0.772727, 0.919192, 0.79798 ],
       [0.269663, 0.772727, 0.343434, 0.79798 ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.11236 , 0.079545, 0.212121, 0.191919],
       [0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ]], dtype=float32)

In [137]:
np.max(bbs, axis=(0, 1))[np.newaxis, np.newaxis, :]

array([[[89., 88., 99., 99.]]], dtype=float32)

In [ ]:
data = ObjectCategoryList.from_df(dataset) \
    .split_by_rand_pct(valid_pct=0.2, seed=123) \
    .label_from()

balls_cf_stats = data.batch_stats()
dataset =  
                  .databunch(bs=64) \
                  .normalize(balls_cf_stats) \

In [ ]:
def init_model():
    
def conv_layer():
    

def build_model():
    